[platformio]
src_dir = .
include_dir = .
test_dir = Core/Test
default_envs=release

[env:tests]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=
    -ICore/Inc
    -ICore/Inc/acquisinator
    -lm
build_src_filter =
    +<Core/Src/acquisinator/>

[env:release]
platform = ststm32
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = disco_f334c8
board_build.ldscript = STM32F334XX_FLASH_SHIFTED.ld

upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameters
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false

build_src_filter = 
    +<Core/Src/>
    +<Drivers/STM32F3xx_HAL_Driver/Src/>
    -<Drivers/STM32F3xx_HAL_Driver/Src/*_template.c>
    +<Core/Src/acquisinator/>
    +<*.s>
build_flags = 
    -DUSE_HAL_DRIVER
    -std=gnu23
    -DSTM32F334x8
    -ICore/Inc
    -ICore/Inc/acquisinator
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F3xx_HAL_Driver/Inc
    -IDrivers/STM32F3xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32F3xx/Include

lib_deps = 
    https://github.com/eagletrt/libcan-sw.git
	https://github.com/eagletrt/libpal-sw.git#v0.1.0


[env:no-shift]
platform = ststm32
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = disco_f334c8
board_build.ldscript = STM32F334XX_FLASH.ld

upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

build_src_filter = 
    +<Core/Src/>
    +<Drivers/STM32F3xx_HAL_Driver/Src/>
    -<Drivers/STM32F3xx_HAL_Driver/Src/*_template.c>
    +<Core/Src/acquisinator/>
    +<*.s>
build_flags = 
    -DUSE_HAL_DRIVER
    -std=gnu23
    -DSTM32F334x8
    -ICore/Inc
    -ICore/Inc/acquisinator
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F3xx_HAL_Driver/Inc
    -IDrivers/STM32F3xx_HAL_Driver/Inc/Legacy
    -IDrivers/CMSIS/Device/ST/STM32F3xx/Include

lib_deps = 
    https://github.com/eagletrt/libcan-sw.git
	https://github.com/eagletrt/libpal-sw.git#v0.1.0

[env:bootloader]
platform = ststm32
platform_packages =
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200

board = disco_f334c8
board_build.ldscript = STM32F334XX_FLASH.ld

upload_protocol = custom
upload_command = STM32_Programmer_CLI -c port=SWD mode=Normal -d "$BUILD_DIR/firmware.elf" -v -rst

build_src_filter = 
    +<acquisinator-sw-bootloader/Core/Src/>
    +<acquisinator-sw-bootloader/Drivers/STM32F3xx_HAL_Driver/Src/>
    -<acquisinator-sw-bootloader/Drivers/STM32F3xx_HAL_Driver/Src/*_template.c>
    +<acquisinator-sw-bootloader/*.s>

build_flags = 
    -DUSE_HAL_DRIVER
    -DUSE_FULL_LL_DRIVER
    -std=gnu23
    -DSTM32F334x8
    -Iacquisinator-sw-bootloader/Core/Inc
    -Iacquisinator-sw-bootloader/Drivers/CMSIS/Include
    -Iacquisinator-sw-bootloader/Drivers/STM32F3xx_HAL_Driver/Inc
    -Iacquisinator-sw-bootloader/Drivers/STM32F3xx_HAL_Driver/Inc/Legacy
    -Iacquisinator-sw-bootloader/Drivers/CMSIS/Device/ST/STM32F3xx/Include