/******************************************************************************
Finite State Machine
Project: acquisinator_fsm.dot
Description: acquisinator_fsm

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2025-09-11 16:56:14 +0200
Generated from: acquisinator.dot
The finite state machine has:
  6 states
  9 transition functions

******************************************************************************/


#ifndef ACQUISINATOR_H
#define ACQUISINATOR_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
  STATE_INIT = 0,  
  STATE_IDLE,  
  STATE_FATAL,  
  STATE_RUN,  
  STATE_FLASH,  
  STATE_CALIBRATION,  
  NUM_STATES,
  NO_CHANGE
} state_t;

// State human-readable names
extern const char *state_names[];

// State function and state transition prototypes
typedef state_t state_func_t(state_data_t *data);
typedef void transition_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_init(state_data_t *data);
// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_IDLE, STATE_RUN, STATE_FATAL, STATE_FLASH, STATE_CALIBRATION
state_t do_idle(state_data_t *data);
// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FATAL
state_t do_fatal(state_data_t *data);
// Function to be executed in state run
// valid return states: NO_CHANGE, STATE_IDLE, STATE_RUN, STATE_FATAL
state_t do_running(state_data_t *data);
// Function to be executed in state flash
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FATAL, STATE_FLASH
state_t do_flash(state_data_t *data);
// Function to be executed in state calibration
// valid return states: NO_CHANGE, STATE_IDLE, STATE_FATAL, STATE_CALIBRATION
state_t do_calibration(state_data_t *data);


// List of state functions
extern state_func_t *const state_table[NUM_STATES];


// Transition functions
void init_to_idle(state_data_t *data);
void to_fatal(state_data_t *data);
void stay(state_data_t *data);
void idle_to_run(state_data_t *data);
void idle_to_flash(state_data_t *data);
void idle_to_calibration(state_data_t *data);
void run_to_idle(state_data_t *data);
void flash_to_idle(state_data_t *data);
void calibration_to_idle(state_data_t *data);

// Table of transition functions
extern transition_func_t *const transition_table[NUM_STATES][NUM_STATES];

// state manager
state_t run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // ACQUISINATOR_H
