#ifndef ACQUISINATOR_ID_H
#define ACQUISINATOR_ID_H

// #define ACQUISINATOR_ID_0  (0U) // SHOULD NOT BE USED!!! IDs START FROM 1!!!
#define ACQUISINATOR_ID_1  (1U)
#define ACQUISINATOR_ID_2  (2U)
#define ACQUISINATOR_ID_3  (3U)
#define ACQUISINATOR_ID_4  (4U)
#define ACQUISINATOR_ID_5  (5U)
#define ACQUISINATOR_ID_6  (6U)
#define ACQUISINATOR_ID_7  (7U)
#define ACQUISINATOR_ID_8  (8U)
#define ACQUISINATOR_ID_9  (9U)
#define ACQUISINATOR_ID_10 (10U)
#define ACQUISINATOR_ID_11 (11U)
#define ACQUISINATOR_ID_12 (12U)
#define ACQUISINATOR_ID_13 (13U)
#define ACQUISINATOR_ID_14 (14U)
#define ACQUISINATOR_ID_15 (15U)
#define ACQUISINATOR_ID_16 (16U)
#define ACQUISINATOR_ID_17 (17U)
#define ACQUISINATOR_ID_18 (18U)
#define ACQUISINATOR_ID_19 (19U)
#define ACQUISINATOR_ID_20 (20U)
#define ACQUISINATOR_ID_21 (21U)
#define ACQUISINATOR_ID_22 (22U)
#define ACQUISINATOR_ID_23 (23U)
#define ACQUISINATOR_ID_24 (24U)
#define ACQUISINATOR_ID_25 (25U)
#define ACQUISINATOR_ID_26 (26U)
#define ACQUISINATOR_ID_27 (27U)
#define ACQUISINATOR_ID_28 (28U)
#define ACQUISINATOR_ID_29 (29U)
#define ACQUISINATOR_ID_30 (30U)
#define ACQUISINATOR_ID_31 (31U)

#define ACQUISINATOR_ID (ACQUISINATOR_ID_31)

#if ACQUISINATOR_ID == 0
#error INVALID ACQUISINATOR_ID == 0
#endif

#if ACQUISINATOR_ID == ACQUISINATOR_ID_0
#error INVALID ACQUISINATOR_ID == ACQUISINATOR_ID_0
#endif

#endif // ACQUISINATOR_ID_H